jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: chocolateen
          name: Hugo
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: vaugie_g
          name: Garance
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: i_dont_know
          name: Jeremy
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: nasso
          name: Nassim
          password: ${USER_NASSO_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - name: "admin"
          assignments:
            - "chocolateen"
          description: "Marvin master"
          permissions:
          - "Overall/Administer"
        - name: "ape"
          assignments:
            - "i_dont_know"
          description: "Pedagogical team member"
          permissions:
          - "Job/Build"
          - "Job/Workspace"
        - name: "assist"
          description: "Assistant"
          assignments:
            - "nasso"
          permissions:
          - "Job/Read"
          - "Job/Workspace"
        - name: "gorilla"
          description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
          assignments:
            - "vaugie_g"
          permissions:
          - "Job/Cancel"
          - "Job/Move"
          - "Job/Build"
          - "Job/Delete"
          - "Job/Create"
          - "Job/Configure"
          - "Job/Workspace"
jobs:
  - file: /var/jenkins_home/job_dsl.groovy
